version: '3.1'

services:
 # Local Services -----------------------
  config-service:
     build:
       context: ./config-service
       dockerfile: ./Dockerfile
     image: config-service
     ports:
     - 8888:8888
     container_name: config-service

  eureka-service:
     build:
       context: ./eureka-service
       dockerfile: ./Dockerfile
     image: eureka-service
     depends_on:
     - config-service
     container_name: eureka-service

  auth-service:
     build:
       context: ./auth-service
       dockerfile: ./Dockerfile
     image: auth-service
     depends_on:
     - mysql-db
     - config-service
     container_name: auth-service

  cart-service:
     build:
       context: ./cart-service
       dockerfile: ./Dockerfile
     image: cart-service
     depends_on:
     - mysql-db
     - config-service
     container_name: cart-service

  customer-service:
     build:
       context: ./customer-service
       dockerfile: ./Dockerfile
     image: customer-service
     depends_on:
     - mysql-db
     - config-service
     container_name: customer-service

  order-service:
     build:
       context: ./order-service
       dockerfile: ./Dockerfile
     image: order-service
     depends_on:
     - mysql-db
     - config-service
     container_name: order-service

  product-service:
     build:
       context: ./product-service
       dockerfile: ./Dockerfile
     image: product-service
     depends_on:
     - mysql-db
     - elasticsearch
     - config-service
     container_name: product-service

  gateway-service:
     build:
       context: ./gateway-service
       dockerfile: ./Dockerfile
     image: gateway-service
     depends_on:
     - eureka-service
     - config-service
     container_name: gateway-service

  hystrix-dashboard:
     build:
       context: ./hystrix-dashboard
       dockerfile: ./Dockerfile
     image: hystrix-dashboard
     depends_on:
     - config-service
     container_name: hystrix-dashboard

#database
  mysql-db:
    image: mysql:5.5
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    command: --init-file /data/application/init.sql

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
        MONGO_INITDB_DATABASE: "shoppingDb"
        MONGODB_USERNAME: "mongo"
        MONGODB_PASSWORD: "mongo"
    container_name: mongo

  msrabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  elasticsearch:
    image: elasticsearch:7.14.1
    ports:
      - 9201:9200
      - 9300:9300
    environment:
      discovery.type: single-node

  shopping-s3:
    image: minio/minio:RELEASE.2021-02-11T08-23-43Z
    ports:
      - 9000:9000
    environment:
      MINIO_ROOT_USER: shopping-minio
      MINIO_ROOT_PASSWORD: shopping-minio
    command: server /data

