#https://cloud.spring.io/spring-cloud-gateway/reference/html/
server:
  port: ${SERVER_PORT:8088}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/users/**
            - Path=/api/address/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
            - name: Hystrix
              args:
                name: customer-service
                fallbackUri: forward:/fb/users

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
            - name: Hystrix
              args:
                name: product-service
                fallbackUri: forward:/fb/product

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8500}/eureka/
    register-with-eureka: false
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
