#https://cloud.spring.io/spring-cloud-gateway/reference/html/
server:
  port: ${SERVER_PORT:8088}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /$\{segment}
            - name: Hystrix
              args:
                name: customer-service
                fallbackUri: forward:/fb/users

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**
          filters:
            - RewritePath=/api/products/(?<segment>.*), /$\{segment}
            - name: Hystrix
              args:
                name: product-service
                fallbackUri: forward:/fb/products

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /$\{segment}
            - name: Hystrix
              args:
                name: auth-service
                fallbackUri: forward:/fb/auth

        - id: cart-service
          uri: lb://CART-SERVICE
          predicates:
            - Path=api/cart/**
          filters:
            - RewritePath=/api/cart/(?<segment>.*), /$\{segment}
            - name: Hystrix
              args:
                name: cart-service
                fallbackUri: forward:/fb/cart

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=api/orders/**
          filters:
            - RewritePath=/api/orders/(?<segment>.*), /$\{segment}
            - name: Hystrix
              args:
                name: order-service
                fallbackUri: forward:/fb/order



eureka:
  client:
    instance:
      hostname: ${EUREKA_SERVER_HOSTNAME:localhost}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8500/eureka/}


management:
  endpoints:
    web:
      exposure:
        include: "*"
