server:
  port: 9090

spring:
  application:
    name: cart-service
  data:
    mongodb:
      authentication-database: admin
      auto-index-creation: true
      database: cartDb
      host: localhost
      port: 27017


#  autoconfigure:
#    exclude: org:springframework:boot:autoconfigure:jdbc:DataSourceAutoConfiguration

axon:
  axonserver:
    servers: 192.168.99.100:8124


#eureka:
#  client:
#    instance:
#      hostname: ${EUREKA_SERVER_HOSTNAME:localhost}
#    serviceUrl:
#      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8500/eureka/}
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"

